server:
  port: 8081
spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: none
      default_schema: NUANBODB
    show-sql: true
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        opaque-token:
          client-id: ${KEYCLOAK_CLIENT_ID}
          client-secret: ${KEYCLOAK_CLIENT_SECRET}
          introspection-uri: ${KEYCLOAK_INTROSPECTION_URI}
client:
  keycloak:
    client-id: ${KEYCLOAK_CLIENT_ID}
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
    introspection-uri: ${KEYCLOAK_INTROSPECTION_URI}
logging:
  config: classpath:log/log4j2.properties
config:
  application:
    rateLimited:
      number-max-request: 10000
      range-time-request: 30000
      waiting-time: 60